### ISSUE TITLE
Comments on the draft

### ISSUE THREAD

**Issue by tireddy2** [danwing/cidfi#3]
(1) Section 4 may also want to discuss a scenario where the client is aware of the network identity (e.g., "example.net").  In this case, the DNS query will be "_cidfi-aware.example.net". 

(2) I suggest removing Appendix A (it has privacy issues, revealing network identity to the server).

(3)Section 5.2, the client could authorize the CIDFI network elements if it has sufficient reputation (e.g., it would work for Mobile Networks, Enterprise networks etc.). It would avoid end-user intervention in certain deployments.

(4) Section 6.2, in the sequence diagram, replace "HTTP" with "HTTPS"

(5) We should explain the Nonce mechanism prevents a passive attacker but not an active attacker. I mean an active attacker not interested in disrupting the QUIC connection but leveraging this mechanism to learn about the network characteristics.

(6) Section 6.3> We should say PKIX validatation of CIDFI network elements. The client uses default system or application PKI trust anchors unless configured otherwise to use explicit trust anchors.

(7) Any specific reason for choosing STUN request instead of STUN indications ?
   We should go with STUN indications as response is not required. Further, STUN requests are re-transmitted by default.

(8) Note: we may want to use [CoAP] for the client->network communication and over the CIDFI-dedicated QUIC stream between the QUIC client and QUIC server. 

Comment> I think you mean use to "to use [CBOR] for the client->network..."

(9)  I don't know if kaippallimalil-tsvwg-media-hdr-wireless will progress. Can we avoid the dependency on kaippallimalil-tsvwg-media-hdr-wireless ?

**Comment by boucadair** [comment]
oudated
