### ISSUE TITLE
metadata is not needed for each packet

### ISSUE THREAD

**Issue by boucadair** [danwing/cidfi#34]
https://github.com/danwing/cidfi/blob/fc1c5d954810610bb9802f95868738c9217f638d/draft-wing-cidfi.md?plain=1#L150

I thought that I have modified this to cover cases where only a subset of packets are enriched, not all. Any reason why we have all to be so?

**Comment by danwing** [comment]
You're right -- we don't need every CID mapped to metadata.  Also as written, that sentence implies the metadata is *in* the IP packet itself.  With CIDFI, that never occurs.  Rather, it's a mapping of CID to metadata.

And, yes, there is no reason to have every CID mapped to metadata.  Those would receive 'default' treatment (whatever that is).

**Comment by boucadair** [comment]
> You're right -- we don't need every CID mapped to metadata. Also as written, that sentence implies the metadata is _in_ the IP packet itself. With CIDFI, that never occurs. Rather, it's a mapping of CID to metadata.
> 
> And, yes, there is no reason to have every CID mapped to metadata. Those would receive 'default' treatment (whatever that is).

Agree. I trust you will change the text. Thanks.

**Comment by danwing** [comment]
Fixed in #35
