### ISSUE TITLE
Packet type in Figure 6

### ISSUE THREAD

**Issue by boucadair** [danwing/cidfi#44]
https://github.com/danwing/cidfi/blob/602c0125c6d257b180f7f9cd711a05d1be2a28ef/draft-wing-cidfi.md?plain=1#L672

Why is this an initial packet? This should be any QUIC packet with SCID=xyz + signaled 4-uple. No?

Also, why do we have an OK right after?

**Comment by danwing** [comment]
On Nov 22, 2023, at 1:42 AM, Med ***@***.***> wrote:﻿
https://github.com/danwing/cidfi/blob/602c0125c6d257b180f7f9cd711a05d1be2a28ef/draft-wing-cidfi.md?plain=1#L672
Why is this an initial packet? This should be any QUIC packet with SCID=xyz + signaled 4-uple. No?Agreed, it could be a connection migration to this network.  But really we don’t need a QUIC exchange first; we can avoid showing that if it clarifies things to not show QUIC initial handshake. 
Also, why do we have an OK right after?The Ok shows the server supports CIDFI.  Now that the server is optional for CIDFI, we don’t need the Ok. -d

**Comment by boucadair** [comment]
Ok, let's then update the figure. Thanks.

**Comment by danwing** [comment]
Fixed in PR #49
